`timescale 1ns / 1ps
//============================================================================
// GPS C/A Code Generator: Single shared ROM for all 32 PRNs
//
// Address map: {5-bit PRN, 10-bit chip_index} = 15-bit address
// Total size: 32 × 1023 = 32,736 bits ≈ 4 KB (fits in 1 BRAM36)
//
// Python equivalent:
//   code_chip = code_mem[prn][chip_idx]
//============================================================================

module ca_code_gen #(
    parameter PRN_BITS  = 5,
    parameter CHIP_BITS = 10,
    parameter CODE_LENGTH = 1023,
    parameter ROM_ADDR_WIDTH = 15  // 5 + 10 = 15 bits
)(
    input  wire                  clk,
    input  wire [PRN_BITS-1:0]   prn_sel,
    input  wire [CHIP_BITS-1:0]  chip_idx,
    output reg                   code_chip     // 1 or 0
);

    // Combined address: PRN in upper bits, chip index in lower bits
    wire [ROM_ADDR_WIDTH-1:0] rom_addr = {prn_sel, chip_idx};
    
    // Single ROM for all 32 PRNs
    // In Vivado: Use Block Memory Generator IP with depth=32768, width=1
    // For simulation: Initialize from a single .hex file
    reg [0:0] code_rom [0:(1<<ROM_ADDR_WIDTH)-1];
    
    // Initialize ROM from hex file (generated by Python script)
    initial begin
        $readmemh("ca_code_all_prns.hex", code_rom);
    end
    
    // Registered output (1 cycle latency)
    always @(posedge clk) begin
        code_chip <= code_rom[rom_addr][0];
    end

endmodule