`timescale 1ns / 1ps

module tb_acquisition_engine;

    // Parameters
    parameter CLK_PERIOD = 10; // 100 MHz clock
    parameter FFT_SIZE = 4096;
    parameter DATA_WIDTH = 18;
    parameter PHASE_BITS = 48;

    // Testbench Signals
    reg clk;
    reg rst_n;
    reg start;
    wire done;
    wire [4:0] detected_prn;
    wire signed [15:0] detected_doppler;
    wire [11:0] detected_code_phase;
    wire [31:0] peak_magnitude;

    // Stimulus Signals
    reg signed [15:0] stim_i;
    reg signed [15:0] stim_q;
    reg stim_valid;

    // Expected Results (Set these to match your stimulus)
    parameter EXP_PRN = 5'd1;
    parameter signed [15:0] EXP_DOPPLER = 1500; // Hz
    parameter [11:0] EXP_CODE_PHASE = 234;      // chips

    // Instantiate the Unit Under Test (UUT)
    acquisition_engine #(
        .FFT_SIZE(FFT_SIZE),
        .DATA_WIDTH(DATA_WIDTH),
        .PHASE_BITS(PHASE_BITS)
    ) uut (
        .clk(clk),
        .rst_n(rst_n),
        .start(start),
        .done(done),
        .detected_prn(detected_prn),
        .detected_doppler(detected_doppler),
        .detected_code_phase(detected_code_phase),
        .peak_magnitude(peak_magnitude),
        .i_sample(stim_i),
        .q_sample(stim_q),
        .sample_valid(stim_valid),
        .prn_sel(EXP_PRN),
        .carrier_freq_word(48'h000010624DD2F1) // Pre-calculated for 1500 Hz @ 4 MHz
    );

    // Clock Generation
    initial begin
        clk = 0;
        forever #(CLK_PERIOD/2) clk = ~clk;
    end

    // Stimulus Generation
    initial begin
        // Initialize
        rst_n = 0;
        start = 0;
        stim_i = 0;
        stim_q = 0;
        stim_valid = 0;

        // Reset
        #(CLK_PERIOD * 5);
        rst_n = 1;
        #(CLK_PERIOD * 5);

        // Wait for ROMs to load (simulation delay)
        #10000;

        // Start Acquisition
        start = 1;
        #(CLK_PERIOD);
        start = 0;

        // Feed 4096 samples of synthetic GPS signal
        // NOTE: For a full test, you would instantiate your gps_signal_gen module here.
        // For now, we will feed a simple repeating pattern or load from a file.
        // To keep this testbench self-contained, let's load from a file generated by Python.
        
        $display("Starting stimulus playback...");
        play_stimulus_from_file("stimulus_4096_samples.hex");

        // Wait for completion
        wait (done === 1);
        #(CLK_PERIOD * 10);

        // Check Results
        $display("========================================");
        $display("ACQUISITION COMPLETE");
        $display("Detected PRN: %0d (Expected: %0d)", detected_prn, EXP_PRN);
        $display("Detected Doppler: %0d Hz (Expected: %0d Hz)", detected_doppler, EXP_DOPPLER);
        $display("Detected Code Phase: %0d chips (Expected: %0d chips)", detected_code_phase, EXP_CODE_PHASE);
        $display("Peak Magnitude: %0d", peak_magnitude);
        $display("========================================");

        if (detected_prn == EXP_PRN && detected_code_phase == EXP_CODE_PHASE) begin
            $display("✅ TEST PASSED: Acquisition successfully locked!");
        end else begin
            $display("❌ TEST FAILED: Acquisition did not lock to expected parameters.");
        end

        $finish;
    end

    // Task to play back stimulus from a hex file
    task play_stimulus_from_file(input string filename);
        integer file, i;
        reg [31:0] stim_word; // 16-bit I + 16-bit Q
        
        file = $fopen(filename, "r");
        if (file == 0) begin
            $display("⚠️ Warning: Could not open %s. Feeding zeros.", filename);
            for (i = 0; i < FFT_SIZE; i = i + 1) begin
                @(posedge clk);
                stim_valid <= 1;
                stim_i <= 16'sd0;
                stim_q <= 16'sd0;
            end
            stim_valid <= 0;
        end else begin
            for (i = 0; i < FFT_SIZE; i = i + 1) begin
                $fscanf(file, "%h", stim_word);
                @(posedge clk);
                stim_valid <= 1;
                stim_i <= stim_word[31:16]; // Upper 16 bits = I
                stim_q <= stim_word[15:0];  // Lower 16 bits = Q
            end
            stim_valid <= 0;
            $fclose(file);
        end
    endtask

endmodule